# Generated by Django 2.1 on 2021-06-06 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('budget', models.FloatField(default=0)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'travel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_id', models.CharField(max_length=21, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=31, null=True)),
                ('fullname', models.CharField(blank=True, max_length=127, null=True)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=511, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Travel'),
        ),
    ]
