# Generated by Django 2.1 on 2021-06-06 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('travel_name', models.CharField(blank=True, max_length=127, null=True)),
                ('travel_boarding_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('travel_departure_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('travel_description', models.TextField(blank=True, default=None, null=True)),
                ('travel_budget', models.FloatField(blank=True, null=True)),
                ('travel_url', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
            options={
                'db_table': 'travel_log',
            },
        ),
        migrations.AddField(
            model_name='travel',
            name='boarding_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
    ]
